name: 'softdev-action'
description: 'A GitHub Action to track weekly pushes.'
author: 'UPE SoftDev'
branding:
  icon: user-check
  color: green
inputs:
  spreadsheetId:
    description: 'The id of the spreadsheet to use'
    required: true
  outputs:
  results:
    description: 'The results of all commands as an array'
runs:
  using: 'node12'
  main: 'dist/index.js'