name: 'softdev-action'
description: 'A GitHub Action to track weekly pushes.'
author: 'UPE SoftDev'
branding:
  icon: user-check
  color: green
inputs:
  spreadsheetId:
    description: 'The id of the spreadsheet to use'
    required: true
  worksheetTitle:
    description: 'The title of the worksheet to use'
    required: true
  actor:
    description: 'The user who committed'
    required: true
  repository:
    description: 'The github repository being committed to'
    required: true
  sha:
    description: 'The sha of the commit'
    required: true
outputs:
  results:
    description: 'The results of all commands as an array'
runs:
  using: 'node12'
  main: 'dist/index.js'